name: tests

on:
  push:
  pull_request:

jobs:
  laravel:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        laravel: ['5.5.*', '5.6.*', '5.7.*', '5.8.*', '6.*', '7.*', '12.*']
        php: [7.2, '8.2', '8.3', '8.4']
        include:
          - laravel: 6.*
            php: 7.3
          - laravel: 6.*
            php: 7.4
          - laravel: 6.*
            php: 8.0
          - laravel: 7.*
            php: 7.3
          - laravel: 7.*
            php: 7.4
          - laravel: 7.*
            php: 8.0
          - laravel: 8.*
            php: 7.3
          - laravel: 8.*
            php: 7.4
          - laravel: 8.*
            php: 8.0
          - laravel: 8.*
            php: 8.1
          - laravel: 9.*
            php: 8.0
          - laravel: 9.*
            php: 8.1
          - laravel: 9.*
            php: 8.2
          - laravel: 10.*
            php: 8.1
          - laravel: 10.*
            php: 8.2
          - laravel: 10.*
            php: 8.3
          - laravel: 11.*
            php: 8.2
          - laravel: 11.*
            php: 8.3
          - laravel: 12.*
            php: '8.2'
        exclude:
          - laravel: 12.*
            php: 7.2


    name: PHPUnit on Laravel ${{ matrix.laravel }} / PHP ${{ matrix.php }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2


      - name: Install dependencies
        run: |
          composer require laravel/laravel:"${{ matrix.laravel }}" --dev --no-update
          composer install --prefer-dist --no-interaction --no-progress


      - name: Run tests
        run: composer test-laravel

  lumen:
    runs-on: ubuntu-latest


    strategy:
      fail-fast: true
      matrix:
        lumen: ['5.5.*', '5.6.*', '5.7.*', '5.8.*', '6.*', '7.*']
        php: [7.2, '8.2', '8.3', '8.4']
        include:
          - lumen: 6.*
            php: 7.3
          - lumen: 6.*
            php: 7.4
          - lumen: 7.*
            php: 7.3
          - lumen: 7.*
            php: 7.4
          - lumen: 8.*
            php: 7.3
          - lumen: 8.*
            php: 7.4
          - lumen: 8.*
            php: 8.0
          - lumen: 8.*
            php: 8.1
          - lumen: 9.*
            php: 8.0
          - lumen: 9.*
            php: 8.1
          - lumen: 9.*
            php: 8.2


    name: PHPUnit on Lumen ${{ matrix.lumen }} / PHP ${{ matrix.php }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2


      - name: Install dependencies
        run: |
          composer require laravel/lumen:"${{ matrix.lumen }}" --dev --no-update
          composer install --prefer-dist --no-interaction --no-progress


      - name: Run tests
        run: composer test-lumen
