name: tests

on:
  push:
  pull_request:

jobs:
  laravel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        laravel: [ 5.5.*, 5.6.*, 5.7.*, 5.8.*, 6.*, 7.* ]
        php: [ 7.2 ]
        include:
          - laravel: 6.*
            php: 7.3
          - laravel: 6.*
            php: 7.4
          - laravel: 6.*
            php: 8.0
          - laravel: 7.*
            php: 7.3
          - laravel: 7.*
            php: 7.4
          - laravel: 7.*
            php: 8.0
          - laravel: 8.*
            php: 7.3
          - laravel: 8.*
            php: 7.4
          - laravel: 8.*
            php: 8.0
          - laravel: 8.*
            php: 8.1
          - laravel: 9.*
            php: 8.0
          - laravel: 9.*
            php: 8.1
          - laravel: 9.*
            php: 8.2
          - laravel: 10.*
            php: 8.1
          - laravel: 10.*
            php: 8.2
          - laravel: 10.*
            php: 8.3
          - laravel: 11.*
            php: 8.2
          - laravel: 11.*
            php: 8.3
          - laravel: 12.*
            php: 8.2
          - laravel: 12.*
            php: 8.3
    name: PHPUnit on Laravel ${{ matrix.laravel }} / PHP ${{ matrix.php }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer require laravel/laravel:"${{ matrix.laravel }}" --dev --no-update
          composer install --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: composer test-laravel
